sudo: required

services:
  - docker

before_install:
  - docker pull lorenzb/hydra

script:
  - ls
  - pwd
  - docker run -v $PWD:/repo lorenzb/hydra bash -c "cp -r /repo /repo2  && cd /repo2/ && python3.6 -m pip install -r requirements.txt && python3.6 run_all_tests.py"
