name: instrumenter
version: 0.1.0
synopsis: Hydra instrumenter
description: See <thehydra.io> and the README at <https://github.com/IC3Hydra/Hydra>
maintainer: <lorenzb@ethz.ch>
github: IC3Hydra/Hydra/hydra/instrumenter
category: Development
#extra-source-files:
#  - CHANGELOG.md

ghc-options: -Wunused-imports -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

dependencies:
  - base >= 4.7 && < 5
  - attoparsec
  - bytestring
  - containers
  - cryptonite
  - optparse-applicative
  - parsec
  - relapse >= 1.0.0.0
  - text

library:
  source-dirs: src
  exposed-modules:
    - EVM.Address
    - EVM.Bytecode
    - EVM.BytecodePlus
    - EVM.GenericInitcode
    - EVM.Instrumentation
    - EVM.Instrumentation.Common
    - EVM.Instrumentation.HeadOne
    - EVM.Instrumentation.HeadN
    - EVM.Instrumentation.Metacontract
    - EVM.While
    - EVM.While.Macros
    - Util
  other-modules:

executables:
  instrumenter-exe:
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    source-dirs:
      - app
    dependencies:
      - instrumenter
  whiletestprogs-exe:
    main: WhileTestProgs.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    source-dirs:
      - app
    dependencies:
      - instrumenter

tests:
  spec:
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - instrumenter
      - bytestring
      - QuickCheck
      - tasty
      - tasty-quickcheck
      - tasty-smallcheck
      - tasty-hunit